version: "3"
services:
  myapp:
    build: .
    container_name: myapp_container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - myredis
  myredis:
    image: redis:6.0
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379